sudo: required

language: python

services:
 - docker

before_install:
 - docker pull quay.io/pypa/manylinux1_x86_64
 - docker run -v $PWD:/project quay.io/pypa/manylinux1_x86_64 sh project/build.sh

script:
 - docker run quay.io/pypa/manylinux1_x86_64 ls
 
deploy:
  provider: pypi
  user: ahnitz
  password:
    secure: "JdYiMmD7mipMrfGGn9y+z3HCkHKCnF6dC6Vz5tkZvNTUarbjKiB+usnPcagJh41/cvY1U1lUb3IcI0DDk3RX70Jbh0VjGqi0fn866dAcYtDNLzRg0hyDk+OtmmjAS00178ABOBRZEunTTxxLNzbYo2T3WYl9YsN15Nkr1gfXirtsF7hKCoo/+SYT2vy7czhmt44c/4RX4eAgajUeLceudOZuBSKdRzlrDh0aym5kvT98lUDgipsWlZDXkCWLrioZW5NAQqLlnnyZfqwhwRtt3w6KI8Ys2l3GmCLYDpfYfOJTLU1EBk6PH42jgWpVGBGCl4KkS1sMiaxxlYkAOejFvDZmLc3FxhIABdO3ONezEH3+UXxtdgHnTG1zLhdmwKE60qqkpnspepFgKv08kngwdaDihfcOVXf9cZ499ydi1b/KYPMpISxsR8C5jodg3sEbSzn5aSBYucPYYQ322JUTkqu3mtaGEvOIBmTTcD84i6zH3F0kIYoS/PeXF3RiNVM1+gk9WJraW9Uaj+zwVZB4zq7rcm8fHOB58oNAbgy8FE6RMBl6gMneYzWhOGSumpmM2rdWAB+VLg1RyD4d4Qdmm10EuPDMi4TG+wc7zK6VNRUeVkQ7+9nb6qDmsRjiu2fbuNWjRYgvBh6wANuy2AAfu4+q7tgFoFYZIZUV3r1R7gc="
  on:
    tags: true
  distributions: "bdist_wheel"
  skip_cleanup: true
